version: '3.8'

services:
  api:
    build:
      context: .
      labels:
        org.opencontainers.image.created : ${CREATION_DATE}
        org.opencontainers.image.ref.name: express-demo
        org.opencontainers.image.revision: ${REVISION}
        org.opencontainers.image.source: "https://github.com/bjornmagnusson/express-demo"
    image: bjornmagnusson/express-demo
    ports:
      - "8080:3000"
    labels:
      kompose.service.type: LoadBalancer
