[environments]
  [environments.development]
    name = "express-demo"
    namespace = "default"
    wait = false
    watch = true
    watch-delay = 2
    auto-connect = true
    set = ["service.type=LoadBalancer"]
