apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - imageName: express-demo
    workspace: .
    docker: {}
  local: {}
deploy:
  helm:
    releases:
    - name: express-demo
      chartPath: charts/express-demo
      namespace: default
      #valuesFilePath: helm-skaffold-values.yaml
      values:
        #image: skaffold-helm
        image.repository: express-demo
      #setValues get appended to the helm deploy with --set.
      #setValues:
        #ingress.enabled: true
