name: docker image
# This workflow is triggered on pushes to the repository.
on: 
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Collect metadata
        uses: docker/metadata-action@v4
        with:
          images: bjornmagnusson/express-demo
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: bjornmagnusson/express-demo:${{ github.sha }}